grpc:
  client:
    user-service:
      address: static://localhost:6565
      negotiationType: plaintext
    movie-service:
      address: static://localhost:7575
      negotiationType: plaintext
server:
  port: 8080
spring:
  application:
    name: aggregator-service
logging:
  level:
    net.shyshkin: debug